### ISSUE TITLE
I can't get the Basic Usage Synchronous example to work.

### ISSUE THREAD

**Issue by Folaht** [wolf4ood/orientdb-rs#24]
_main.rs_
```
use orientdb_client::{OrientDB}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = OrientDB::connect(("localhost",2424))?;

    let session = client.session("demodb","admin","admin")?;

    let results : Vec<_> = session.query("select from V where id = :param").named(&[("param", &1)]).run()?.collect();


    println!("{:?}", results);

    Ok(())
}
```

_terminal_
```
[folaht@pjehrsohmehj src]$ RUST_BACKTRACE=1 cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.15s
     Running `/home/folaht/Nwaȥ/Êspas dû travaj/neovîm/Âp/sn_grufs/target/debug/sn_grufs`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Pool(Error(Some("")))', /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/orientdb-client-0.5.1/src/sync/network/cluster.rs:42:51
stack backtrace:
   0: rust_begin_unwind
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /home/folaht/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: orientdb_client::sync::network::cluster::ClusterBuilder::build::{{closure}}
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/orientdb-client-0.5.1/src/sync/network/cluster.rs:42:26
   5: core::iter::adapters::map::map_fold::{{closure}}
             at /home/folaht/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:80:28
   6: core::iter::traits::iterator::Iterator::fold
             at /home/folaht/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:2023:21
   7: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /home/folaht/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/adapters/map.rs:120:9
   8: core::iter::traits::iterator::Iterator::for_each
             at /home/folaht/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:678:9
   9: <alloc::vec::Vec<T,A> as alloc::vec::SpecExtend<T,I>>::spec_extend
             at /home/folaht/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2568:17
  10: <alloc::vec::Vec<T> as alloc::vec::SpecFromIterNested<T,I>>::from_iter
             at /home/folaht/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2336:9
  11: <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter
             at /home/folaht/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2451:20
  12: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /home/folaht/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec.rs:2181:9
  13: core::iter::traits::iterator::Iterator::collect
             at /home/folaht/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1670:9
  14: orientdb_client::sync::network::cluster::ClusterBuilder::build
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/orientdb-client-0.5.1/src/sync/network/cluster.rs:37:23
  15: orientdb_client::sync::client::OrientDB::connect
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/orientdb-client-0.5.1/src/sync/client.rs:29:23
  16: sn_grufs::main
             at ./main.rs:18:22
  17: core::ops::function::FnOnce::call_once
             at /home/folaht/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by wolf4ood** [comment]
Hi @Folaht 

thanks for opening this issue. Let me check :)

**Comment by wolf4ood** [comment]
Hi @Folaht 

quick question, do you have OrientDB running on 2424 port? Which version?

Thanks

**Comment by Folaht** [comment]
Ohh... I can't just create an OrientDB database in Rust?
I see.

Let's close this issue then.
